# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x:\work\_DEV\QtTests\pyChezz\pyChezzUI.ui'
#
# Created: Fri Nov 13 14:08:54 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(359, 311)
        Form.setStyleSheet(".blackBG{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(54, 43, 33, 255), stop:1 rgba(70, 61, 51, 255))}.whiteBG{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 255, 196), stop:1 rgb(255, 253, 225))}")
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layTop = QtGui.QHBoxLayout()
        self.layTop.setObjectName("layTop")
        self.leGamePath = QtGui.QLineEdit(Form)
        self.leGamePath.setObjectName("leGamePath")
        self.layTop.addWidget(self.leGamePath)
        self.btnOpen = QtGui.QPushButton(Form)
        self.btnOpen.setObjectName("btnOpen")
        self.layTop.addWidget(self.btnOpen)
        self.verticalLayout.addLayout(self.layTop)
        self.layMain = QtGui.QHBoxLayout()
        self.layMain.setObjectName("layMain")
        self.grdFields = QtGui.QGridLayout()
        self.grdFields.setContentsMargins(10, 10, 10, 10)
        self.grdFields.setSpacing(0)
        self.grdFields.setObjectName("grdFields")
        self.fieldB6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB6.sizePolicy().hasHeightForWidth())
        self.fieldB6.setSizePolicy(sizePolicy)
        self.fieldB6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB6.setObjectName("fieldB6")
        self.grdFields.addWidget(self.fieldB6, 2, 1, 1, 1)
        self.fieldF1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF1.sizePolicy().hasHeightForWidth())
        self.fieldF1.setSizePolicy(sizePolicy)
        self.fieldF1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF1.setObjectName("fieldF1")
        self.grdFields.addWidget(self.fieldF1, 7, 5, 1, 1)
        self.fieldB2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB2.sizePolicy().hasHeightForWidth())
        self.fieldB2.setSizePolicy(sizePolicy)
        self.fieldB2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB2.setObjectName("fieldB2")
        self.grdFields.addWidget(self.fieldB2, 6, 1, 1, 1)
        self.fieldE4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE4.sizePolicy().hasHeightForWidth())
        self.fieldE4.setSizePolicy(sizePolicy)
        self.fieldE4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE4.setObjectName("fieldE4")
        self.grdFields.addWidget(self.fieldE4, 4, 4, 1, 1)
        self.fieldE8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE8.sizePolicy().hasHeightForWidth())
        self.fieldE8.setSizePolicy(sizePolicy)
        self.fieldE8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE8.setObjectName("fieldE8")
        self.grdFields.addWidget(self.fieldE8, 0, 4, 1, 1)
        self.fieldF6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF6.sizePolicy().hasHeightForWidth())
        self.fieldF6.setSizePolicy(sizePolicy)
        self.fieldF6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF6.setObjectName("fieldF6")
        self.grdFields.addWidget(self.fieldF6, 2, 5, 1, 1)
        self.fieldB7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB7.sizePolicy().hasHeightForWidth())
        self.fieldB7.setSizePolicy(sizePolicy)
        self.fieldB7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB7.setObjectName("fieldB7")
        self.grdFields.addWidget(self.fieldB7, 1, 1, 1, 1)
        self.fieldC4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC4.sizePolicy().hasHeightForWidth())
        self.fieldC4.setSizePolicy(sizePolicy)
        self.fieldC4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC4.setObjectName("fieldC4")
        self.grdFields.addWidget(self.fieldC4, 4, 2, 1, 1)
        self.fieldF2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF2.sizePolicy().hasHeightForWidth())
        self.fieldF2.setSizePolicy(sizePolicy)
        self.fieldF2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF2.setObjectName("fieldF2")
        self.grdFields.addWidget(self.fieldF2, 6, 5, 1, 1)
        self.fieldA6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA6.sizePolicy().hasHeightForWidth())
        self.fieldA6.setSizePolicy(sizePolicy)
        self.fieldA6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA6.setObjectName("fieldA6")
        self.grdFields.addWidget(self.fieldA6, 2, 0, 1, 1)
        self.fieldH2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH2.sizePolicy().hasHeightForWidth())
        self.fieldH2.setSizePolicy(sizePolicy)
        self.fieldH2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH2.setObjectName("fieldH2")
        self.grdFields.addWidget(self.fieldH2, 6, 7, 1, 1)
        self.fieldB5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB5.sizePolicy().hasHeightForWidth())
        self.fieldB5.setSizePolicy(sizePolicy)
        self.fieldB5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB5.setObjectName("fieldB5")
        self.grdFields.addWidget(self.fieldB5, 3, 1, 1, 1)
        self.fieldB3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB3.sizePolicy().hasHeightForWidth())
        self.fieldB3.setSizePolicy(sizePolicy)
        self.fieldB3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB3.setObjectName("fieldB3")
        self.grdFields.addWidget(self.fieldB3, 5, 1, 1, 1)
        self.fieldA2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA2.sizePolicy().hasHeightForWidth())
        self.fieldA2.setSizePolicy(sizePolicy)
        self.fieldA2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA2.setObjectName("fieldA2")
        self.grdFields.addWidget(self.fieldA2, 6, 0, 1, 1)
        self.fieldD2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD2.sizePolicy().hasHeightForWidth())
        self.fieldD2.setSizePolicy(sizePolicy)
        self.fieldD2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD2.setObjectName("fieldD2")
        self.grdFields.addWidget(self.fieldD2, 6, 3, 1, 1)
        self.fieldA1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA1.sizePolicy().hasHeightForWidth())
        self.fieldA1.setSizePolicy(sizePolicy)
        self.fieldA1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA1.setObjectName("fieldA1")
        self.grdFields.addWidget(self.fieldA1, 7, 0, 1, 1)
        self.fieldA5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA5.sizePolicy().hasHeightForWidth())
        self.fieldA5.setSizePolicy(sizePolicy)
        self.fieldA5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA5.setObjectName("fieldA5")
        self.grdFields.addWidget(self.fieldA5, 3, 0, 1, 1)
        self.fieldD3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD3.sizePolicy().hasHeightForWidth())
        self.fieldD3.setSizePolicy(sizePolicy)
        self.fieldD3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD3.setObjectName("fieldD3")
        self.grdFields.addWidget(self.fieldD3, 5, 3, 1, 1)
        self.fieldE2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE2.sizePolicy().hasHeightForWidth())
        self.fieldE2.setSizePolicy(sizePolicy)
        self.fieldE2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE2.setObjectName("fieldE2")
        self.grdFields.addWidget(self.fieldE2, 6, 4, 1, 1)
        self.fieldH5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH5.sizePolicy().hasHeightForWidth())
        self.fieldH5.setSizePolicy(sizePolicy)
        self.fieldH5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH5.setObjectName("fieldH5")
        self.grdFields.addWidget(self.fieldH5, 3, 7, 1, 1)
        self.fieldD5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD5.sizePolicy().hasHeightForWidth())
        self.fieldD5.setSizePolicy(sizePolicy)
        self.fieldD5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD5.setObjectName("fieldD5")
        self.grdFields.addWidget(self.fieldD5, 3, 3, 1, 1)
        self.fieldE7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE7.sizePolicy().hasHeightForWidth())
        self.fieldE7.setSizePolicy(sizePolicy)
        self.fieldE7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE7.setObjectName("fieldE7")
        self.grdFields.addWidget(self.fieldE7, 1, 4, 1, 1)
        self.fieldE5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE5.sizePolicy().hasHeightForWidth())
        self.fieldE5.setSizePolicy(sizePolicy)
        self.fieldE5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE5.setObjectName("fieldE5")
        self.grdFields.addWidget(self.fieldE5, 3, 4, 1, 1)
        self.fieldD7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD7.sizePolicy().hasHeightForWidth())
        self.fieldD7.setSizePolicy(sizePolicy)
        self.fieldD7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD7.setObjectName("fieldD7")
        self.grdFields.addWidget(self.fieldD7, 1, 3, 1, 1)
        self.fieldG3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG3.sizePolicy().hasHeightForWidth())
        self.fieldG3.setSizePolicy(sizePolicy)
        self.fieldG3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG3.setObjectName("fieldG3")
        self.grdFields.addWidget(self.fieldG3, 5, 6, 1, 1)
        self.fieldG5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG5.sizePolicy().hasHeightForWidth())
        self.fieldG5.setSizePolicy(sizePolicy)
        self.fieldG5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG5.setObjectName("fieldG5")
        self.grdFields.addWidget(self.fieldG5, 3, 6, 1, 1)
        self.fieldC8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC8.sizePolicy().hasHeightForWidth())
        self.fieldC8.setSizePolicy(sizePolicy)
        self.fieldC8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC8.setObjectName("fieldC8")
        self.grdFields.addWidget(self.fieldC8, 0, 2, 1, 1)
        self.fieldD1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD1.sizePolicy().hasHeightForWidth())
        self.fieldD1.setSizePolicy(sizePolicy)
        self.fieldD1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD1.setObjectName("fieldD1")
        self.grdFields.addWidget(self.fieldD1, 7, 3, 1, 1)
        self.fieldG8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG8.sizePolicy().hasHeightForWidth())
        self.fieldG8.setSizePolicy(sizePolicy)
        self.fieldG8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG8.setObjectName("fieldG8")
        self.grdFields.addWidget(self.fieldG8, 0, 6, 1, 1)
        self.fieldC6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC6.sizePolicy().hasHeightForWidth())
        self.fieldC6.setSizePolicy(sizePolicy)
        self.fieldC6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC6.setObjectName("fieldC6")
        self.grdFields.addWidget(self.fieldC6, 2, 2, 1, 1)
        self.fieldH3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH3.sizePolicy().hasHeightForWidth())
        self.fieldH3.setSizePolicy(sizePolicy)
        self.fieldH3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH3.setObjectName("fieldH3")
        self.grdFields.addWidget(self.fieldH3, 5, 7, 1, 1)
        self.fieldC3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC3.sizePolicy().hasHeightForWidth())
        self.fieldC3.setSizePolicy(sizePolicy)
        self.fieldC3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC3.setObjectName("fieldC3")
        self.grdFields.addWidget(self.fieldC3, 5, 2, 1, 1)
        self.fieldD8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD8.sizePolicy().hasHeightForWidth())
        self.fieldD8.setSizePolicy(sizePolicy)
        self.fieldD8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD8.setObjectName("fieldD8")
        self.grdFields.addWidget(self.fieldD8, 0, 3, 1, 1)
        self.fieldB4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB4.sizePolicy().hasHeightForWidth())
        self.fieldB4.setSizePolicy(sizePolicy)
        self.fieldB4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB4.setObjectName("fieldB4")
        self.grdFields.addWidget(self.fieldB4, 4, 1, 1, 1)
        self.fieldD4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD4.sizePolicy().hasHeightForWidth())
        self.fieldD4.setSizePolicy(sizePolicy)
        self.fieldD4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD4.setObjectName("fieldD4")
        self.grdFields.addWidget(self.fieldD4, 4, 3, 1, 1)
        self.fieldH1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH1.sizePolicy().hasHeightForWidth())
        self.fieldH1.setSizePolicy(sizePolicy)
        self.fieldH1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH1.setObjectName("fieldH1")
        self.grdFields.addWidget(self.fieldH1, 7, 7, 1, 1)
        self.fieldD6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldD6.sizePolicy().hasHeightForWidth())
        self.fieldD6.setSizePolicy(sizePolicy)
        self.fieldD6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldD6.setObjectName("fieldD6")
        self.grdFields.addWidget(self.fieldD6, 2, 3, 1, 1)
        self.fieldG1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG1.sizePolicy().hasHeightForWidth())
        self.fieldG1.setSizePolicy(sizePolicy)
        self.fieldG1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG1.setObjectName("fieldG1")
        self.grdFields.addWidget(self.fieldG1, 7, 6, 1, 1)
        self.fieldC5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC5.sizePolicy().hasHeightForWidth())
        self.fieldC5.setSizePolicy(sizePolicy)
        self.fieldC5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC5.setObjectName("fieldC5")
        self.grdFields.addWidget(self.fieldC5, 3, 2, 1, 1)
        self.fieldF8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF8.sizePolicy().hasHeightForWidth())
        self.fieldF8.setSizePolicy(sizePolicy)
        self.fieldF8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF8.setObjectName("fieldF8")
        self.grdFields.addWidget(self.fieldF8, 0, 5, 1, 1)
        self.fieldC7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC7.sizePolicy().hasHeightForWidth())
        self.fieldC7.setSizePolicy(sizePolicy)
        self.fieldC7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC7.setObjectName("fieldC7")
        self.grdFields.addWidget(self.fieldC7, 1, 2, 1, 1)
        self.fieldA7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA7.sizePolicy().hasHeightForWidth())
        self.fieldA7.setSizePolicy(sizePolicy)
        self.fieldA7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA7.setObjectName("fieldA7")
        self.grdFields.addWidget(self.fieldA7, 1, 0, 1, 1)
        self.fieldG7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG7.sizePolicy().hasHeightForWidth())
        self.fieldG7.setSizePolicy(sizePolicy)
        self.fieldG7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG7.setObjectName("fieldG7")
        self.grdFields.addWidget(self.fieldG7, 1, 6, 1, 1)
        self.fieldH8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH8.sizePolicy().hasHeightForWidth())
        self.fieldH8.setSizePolicy(sizePolicy)
        self.fieldH8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH8.setObjectName("fieldH8")
        self.grdFields.addWidget(self.fieldH8, 0, 7, 1, 1)
        self.fieldE6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE6.sizePolicy().hasHeightForWidth())
        self.fieldE6.setSizePolicy(sizePolicy)
        self.fieldE6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE6.setObjectName("fieldE6")
        self.grdFields.addWidget(self.fieldE6, 2, 4, 1, 1)
        self.fieldC2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC2.sizePolicy().hasHeightForWidth())
        self.fieldC2.setSizePolicy(sizePolicy)
        self.fieldC2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC2.setObjectName("fieldC2")
        self.grdFields.addWidget(self.fieldC2, 6, 2, 1, 1)
        self.fieldG2 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG2.sizePolicy().hasHeightForWidth())
        self.fieldG2.setSizePolicy(sizePolicy)
        self.fieldG2.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG2.setObjectName("fieldG2")
        self.grdFields.addWidget(self.fieldG2, 6, 6, 1, 1)
        self.fieldA4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA4.sizePolicy().hasHeightForWidth())
        self.fieldA4.setSizePolicy(sizePolicy)
        self.fieldA4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA4.setObjectName("fieldA4")
        self.grdFields.addWidget(self.fieldA4, 4, 0, 1, 1)
        self.fieldF4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF4.sizePolicy().hasHeightForWidth())
        self.fieldF4.setSizePolicy(sizePolicy)
        self.fieldF4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF4.setObjectName("fieldF4")
        self.grdFields.addWidget(self.fieldF4, 4, 5, 1, 1)
        self.fieldF5 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF5.sizePolicy().hasHeightForWidth())
        self.fieldF5.setSizePolicy(sizePolicy)
        self.fieldF5.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF5.setObjectName("fieldF5")
        self.grdFields.addWidget(self.fieldF5, 3, 5, 1, 1)
        self.fieldH4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH4.sizePolicy().hasHeightForWidth())
        self.fieldH4.setSizePolicy(sizePolicy)
        self.fieldH4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH4.setObjectName("fieldH4")
        self.grdFields.addWidget(self.fieldH4, 4, 7, 1, 1)
        self.fieldA3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA3.sizePolicy().hasHeightForWidth())
        self.fieldA3.setSizePolicy(sizePolicy)
        self.fieldA3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA3.setObjectName("fieldA3")
        self.grdFields.addWidget(self.fieldA3, 5, 0, 1, 1)
        self.fieldH6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH6.sizePolicy().hasHeightForWidth())
        self.fieldH6.setSizePolicy(sizePolicy)
        self.fieldH6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH6.setObjectName("fieldH6")
        self.grdFields.addWidget(self.fieldH6, 2, 7, 1, 1)
        self.fieldE1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE1.sizePolicy().hasHeightForWidth())
        self.fieldE1.setSizePolicy(sizePolicy)
        self.fieldE1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE1.setObjectName("fieldE1")
        self.grdFields.addWidget(self.fieldE1, 7, 4, 1, 1)
        self.fieldG6 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG6.sizePolicy().hasHeightForWidth())
        self.fieldG6.setSizePolicy(sizePolicy)
        self.fieldG6.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG6.setObjectName("fieldG6")
        self.grdFields.addWidget(self.fieldG6, 2, 6, 1, 1)
        self.fieldC1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldC1.sizePolicy().hasHeightForWidth())
        self.fieldC1.setSizePolicy(sizePolicy)
        self.fieldC1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldC1.setObjectName("fieldC1")
        self.grdFields.addWidget(self.fieldC1, 7, 2, 1, 1)
        self.fieldB8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB8.sizePolicy().hasHeightForWidth())
        self.fieldB8.setSizePolicy(sizePolicy)
        self.fieldB8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB8.setObjectName("fieldB8")
        self.grdFields.addWidget(self.fieldB8, 0, 1, 1, 1)
        self.fieldF7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF7.sizePolicy().hasHeightForWidth())
        self.fieldF7.setSizePolicy(sizePolicy)
        self.fieldF7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF7.setObjectName("fieldF7")
        self.grdFields.addWidget(self.fieldF7, 1, 5, 1, 1)
        self.fieldE3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldE3.sizePolicy().hasHeightForWidth())
        self.fieldE3.setSizePolicy(sizePolicy)
        self.fieldE3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldE3.setObjectName("fieldE3")
        self.grdFields.addWidget(self.fieldE3, 5, 4, 1, 1)
        self.fieldA8 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldA8.sizePolicy().hasHeightForWidth())
        self.fieldA8.setSizePolicy(sizePolicy)
        self.fieldA8.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldA8.setObjectName("fieldA8")
        self.grdFields.addWidget(self.fieldA8, 0, 0, 1, 1)
        self.fieldF3 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldF3.sizePolicy().hasHeightForWidth())
        self.fieldF3.setSizePolicy(sizePolicy)
        self.fieldF3.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldF3.setObjectName("fieldF3")
        self.grdFields.addWidget(self.fieldF3, 5, 5, 1, 1)
        self.fieldB1 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldB1.sizePolicy().hasHeightForWidth())
        self.fieldB1.setSizePolicy(sizePolicy)
        self.fieldB1.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldB1.setObjectName("fieldB1")
        self.grdFields.addWidget(self.fieldB1, 7, 1, 1, 1)
        self.fieldH7 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldH7.sizePolicy().hasHeightForWidth())
        self.fieldH7.setSizePolicy(sizePolicy)
        self.fieldH7.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldH7.setObjectName("fieldH7")
        self.grdFields.addWidget(self.fieldH7, 1, 7, 1, 1)
        self.fieldG4 = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fieldG4.sizePolicy().hasHeightForWidth())
        self.fieldG4.setSizePolicy(sizePolicy)
        self.fieldG4.setMinimumSize(QtCore.QSize(30, 30))
        self.fieldG4.setObjectName("fieldG4")
        self.grdFields.addWidget(self.fieldG4, 4, 6, 1, 1)
        self.layMain.addLayout(self.grdFields)
        self.listView = QtGui.QListView(Form)
        self.listView.setMaximumSize(QtCore.QSize(100, 16777215))
        self.listView.setObjectName("listView")
        self.layMain.addWidget(self.listView)
        self.verticalLayout.addLayout(self.layMain)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "pyChezz", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpen.setText(QtGui.QApplication.translate("Form", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB6.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF1.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB2.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE4.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE8.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF6.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB7.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC4.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF2.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA6.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH2.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB5.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB3.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA2.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD2.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA1.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA5.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD3.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE2.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH5.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD5.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE7.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE5.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD7.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG3.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG5.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC8.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD1.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG8.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC6.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH3.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC3.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD8.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB4.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD4.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH1.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldD6.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG1.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC5.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF8.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC7.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA7.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG7.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH8.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE6.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC2.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG2.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA4.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF4.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF5.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH4.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA3.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH6.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE1.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG6.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldC1.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB8.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF7.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldE3.setProperty("class", QtGui.QApplication.translate("Form", "whiteBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldA8.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldF3.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldB1.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldH7.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))
        self.fieldG4.setProperty("class", QtGui.QApplication.translate("Form", "blackBG", None, QtGui.QApplication.UnicodeUTF8))

